### PR TITLE
fix bug that `rel.metadata` not exists

### PR DESCRIPTION
**Pull request by calfzhou**

### CODE REVIEW

**Comment by rpocklin** [comment]
?

**Comment by Benjamin-Dobell** [comment]
To be specific, this changed in a newer version of Mongoid. Merging it, if even on a branch, would be appreciated.

**Comment by rpocklin** [comment]
Are you looking for someone to maintain this repo?

**Comment by Benjamin-Dobell** [comment]
D'oh! This tripped me up again with a different project.

I can see there are a lot of forks with this change (or similar) applied. We'd all really appreciate it if this could be merged and a new RubyGems release be made.

**Comment by knovoselic** [comment]
@calfzhou Thanks, sorry it took so long to get this merged!

**Comment by knovoselic** [comment]
@Benjamin-Dobell Just pushed a new version which fixes this issue and another one (the gem would remove some other errors on embedded field, e.g. error produced by `validates :field, presence: true`). Sorry it took so long, it will be better from now on.

**Pull request merged**
